//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public System.Guid GroupMemberID { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> GroupCustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual GroupCustomer GroupCustomer { get; set; }
    }
}
