//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInPurchaseAndDonate
    {
        public System.Guid StockInId { get; set; }
        public Nullable<System.Guid> PurchaseOrderId { get; set; }
        public Nullable<System.Guid> StockId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> StockInTypeId { get; set; }
        public string StockInCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Status { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> AccountingDate { get; set; }
        public string PercentComplete { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual StockIn StockIn { get; set; }
    }
}
