//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockOut()
        {
            this.StockOutDetail = new HashSet<StockOutDetail>();
        }
    
        public System.Guid StockOutId { get; set; }
        public Nullable<System.Guid> FromStock { get; set; }
        public Nullable<System.Guid> ToStock { get; set; }
        public Nullable<System.Guid> StockOutType { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> SaleOrderId { get; set; }
        public string StockOutCode { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<double> PercentComplete { get; set; }
        public string DestroyReason { get; set; }
        public string ReasonReturn { get; set; }
        public Nullable<decimal> DeliveryTimes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual SaleOrder SaleOrder { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Stock Stock1 { get; set; }
        public virtual StockOutType StockOutType1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutDetail> StockOutDetail { get; set; }
    }
}
