//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutDetail
    {
        public System.Guid StockOutDetailId { get; set; }
        public Nullable<System.Guid> StockOutId { get; set; }
        public Nullable<decimal> Quanlity { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<decimal> Status { get; set; }
    
        public virtual StockOut StockOut { get; set; }
    }
}
