//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockOut()
        {
            this.StockOutDetail = new HashSet<StockOutDetail>();
        }
    
        public System.Guid StockOutId { get; set; }
        public Nullable<System.Guid> StockId { get; set; }
        public Nullable<System.Guid> StockOutType { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string StockOutCode { get; set; }
        public Nullable<decimal> Status { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PercentComplete { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual StockOutType StockOutType1 { get; set; }
        public virtual User User { get; set; }
        public virtual StockOutDestroy StockOutDestroy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutDetail> StockOutDetail { get; set; }
        public virtual StockOutSaleAndDonate StockOutSaleAndDonate { get; set; }
        public virtual StockOutTransfer StockOutTransfer { get; set; }
        public virtual StockOutReturn StockOutReturn { get; set; }
    }
}
