//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInDetail
    {
        public System.Guid StockInDetailID { get; set; }
        public Nullable<System.Guid> StockInId { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<decimal> Quanlity { get; set; }
        public string Note { get; set; }
    
        public virtual StockIn StockIn { get; set; }
    }
}
