//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockManagementEntities : DbContext
    {
        public StockManagementEntities()
            : base("name=StockManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressCustomer> AddressCustomer { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<GroupCustomer> GroupCustomer { get; set; }
        public virtual DbSet<GroupMember> GroupMember { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductOnStock> ProductOnStock { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<ProductUnit> ProductUnit { get; set; }
        public virtual DbSet<province> province { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        public virtual DbSet<SaleOrder> SaleOrder { get; set; }
        public virtual DbSet<SaleOrderDetail> SaleOrderDetail { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockIn> StockIn { get; set; }
        public virtual DbSet<StockInDetail> StockInDetail { get; set; }
        public virtual DbSet<StockInType> StockInType { get; set; }
        public virtual DbSet<StockManager> StockManager { get; set; }
        public virtual DbSet<StockOut> StockOut { get; set; }
        public virtual DbSet<StockOutDetail> StockOutDetail { get; set; }
        public virtual DbSet<StockOutType> StockOutType { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierProduct> SupplierProduct { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPermission> UserPermission { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<ward> ward { get; set; }
        public virtual DbSet<vw_AddressCustomer> vw_AddressCustomer { get; set; }
        public virtual DbSet<vw_ProductOnStock> vw_ProductOnStock { get; set; }
        public virtual DbSet<vw_ProductOnStockDetail> vw_ProductOnStockDetail { get; set; }
        public virtual DbSet<vw_SaleOrder> vw_SaleOrder { get; set; }
        public virtual DbSet<vw_SaleOrderDetail> vw_SaleOrderDetail { get; set; }
        public virtual DbSet<vw_UserPermission> vw_UserPermission { get; set; }
        public virtual DbSet<vw_Product> vw_Product { get; set; }
        public virtual DbSet<vw_PurchaseOrder> vw_PurchaseOrder { get; set; }
        public virtual DbSet<vw_PurchaseOrderDetail> vw_PurchaseOrderDetail { get; set; }
        public virtual DbSet<vw_StockIn> vw_StockIn { get; set; }
        public virtual DbSet<vw_StockOutDetail> vw_StockOutDetail { get; set; }
    }
}
