//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductOnStockDetail
    {
        public System.Guid ProductOnStockId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public Nullable<decimal> RecentQuanlity { get; set; }
        public Nullable<decimal> MaxQuanlity { get; set; }
        public Nullable<decimal> MinQuanlity { get; set; }
        public string SearchString { get; set; }
    }
}
