//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SaleOrder
    {
        public System.Guid SaleOrderDetailId { get; set; }
        public string SaleOrderCode { get; set; }
        public string Customer { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> QuanlityOfCustomer { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.Guid CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public System.Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ShipAddress { get; set; }
        public System.Guid AddressCustomerId { get; set; }
        public string FullAddress { get; set; }
        public Nullable<decimal> NumberPhone { get; set; }
        public System.Guid SaleOrderId { get; set; }
    }
}
