//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StockIn
    {
        public System.Guid StockInId { get; set; }
        public string StockInCode { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<System.DateTime> AccountingDate { get; set; }
        public Nullable<double> PercentComplete { get; set; }
        public string ReasonReturn { get; set; }
        public Nullable<System.Guid> FromStock { get; set; }
        public string FromStockName { get; set; }
        public Nullable<System.Guid> ToStock { get; set; }
        public string ToStockName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.Guid> PurchaseOrderId { get; set; }
        public string PurchaseOrderCode { get; set; }
        public Nullable<System.Guid> StockInTypeId { get; set; }
        public string StockInTypeName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
